In [1]:
from glas_o_mat.dataset import load_data, create_dataset

In [2]:
dataset = load_data()
dataset.activities

,TRANSACTION_ID,CONTAINER_ID,SLIDER_LEVEL,CV_LEVEL,SENSOR_LEVEL,IMAGE_ID,PHONE_ID,RECORDED_AT,COMMENT,IS_EMPTIED,LATITUDE,LONGITUDE,CREATED_AT,UPDATED_AT,ROUTE_ID,LOCATION_ID,MATERIAL_ID,DATE,INTERVAL,EMPTIED_INTERVAL
0,388,1001101102100921111,20,NaN,NaN,1001101102100921111/2023-09-28T11:31:15.634.png,TP1A.220624.014_1,2023-09-27 11:31:16,NaN,1,49.520190,7.712212,2023-10-13 11:18:58.0,NaN,NaN,100110110210092,11,2023-09-27,NaT,NaT
1,383,1001101102100861211,10,NaN,NaN,1001101102100861211/2023-09-28T11:46:23.439.png,TP1A.220624.014_1,2023-09-27 11:46:23,NaN,1,49.520190,7.712212,2023-10-13 11:18:58.0,NaN,NaN,100110110210086,12,2023-09-27,NaT,NaT
2,382,1001101102100861111,30,NaN,NaN,1001101102100861111/2023-09-28T11:46:37.700.png,TP1A.220624.014_1,2023-09-27 11:46:38,NaN,1,49.520190,7.712212,2023-10-13 11:18:58.0,NaN,NaN,100110110210086,11,2023-09-27,NaT,NaT
3,384,1001101102100861311,60,NaN,NaN,1001101102100861311/2023-09-28T11:46:53.244.png,TP1A.220624.014_1,2023-09-27 11:46:53,NaN,0,49.520190,7.712212,2023-10-13 11:18:58.0,NaN,NaN,100110110210086,13,2023-09-27,NaT,NaT
4,444,1001101101100251111,10,NaN,NaN,1001101101100251111/2023-09-29T14:20:36.942.png,TP1A.220624.014_2,2023-09-27 14:20:37,NaN,0,49.440943,7.810645,2023-10-13 11:18:58.0,NaN,NaN,100110110110025,11,2023-09-27,NaT,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38530,61152,1001101101100531212,90,NaN,NaN,1001101101100531212/2024-10-17T14:46:54.523517...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-17 14:46:55,NaN,1,49.494200,49.494200,2024-10-17 12:47:33.0,2024-10-17 12:47:33.0,2024-10-17-1001101101-0,100110110110053,12,2024-10-17,1 days 05:23:18,15 days 00:30:46
38531,61149,1001101101100531111,90,NaN,NaN,1001101101100531111/2024-10-17T14:47:02.646031...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-17 14:47:03,NaN,1,49.494200,49.494200,2024-10-17 12:47:31.0,2024-10-17 12:47:31.0,2024-10-17-1001101101-0,100110110110053,11,2024-10-17,1 days 05:23:56,15 days 00:31:18
38532,61150,1001101101100531112,90,NaN,NaN,1001101101100531112/2024-10-17T14:47:10.767846...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-17 14:47:11,NaN,1,49.494200,49.494200,2024-10-17 12:47:32.0,2024-10-17 12:47:32.0,2024-10-17-1001101101-0,100110110110053,11,2024-10-17,1 days 05:23:53,15 days 00:31:18
38533,61153,1001101101100531311,20,NaN,NaN,1001101101100531311/2024-10-17T14:47:19.611355...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-17 14:47:20,NaN,0,49.494200,49.494200,2024-10-17 12:47:34.0,2024-10-17 12:47:34.0,2024-10-17-1001101101-0,100110110110053,13,2024-10-17,1 days 05:24:33,NaT
38534,61154,1001101101100531312,10,NaN,NaN,1001101101100531312/2024-10-17T14:47:27.912185...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-17 14:47:28,NaN,0,49.494200,49.494200,2024-10-17 12:47:35.0,2024-10-17 12:47:35.0,2024-10-17-1001101101-0,100110110110053,13,2024-10-17,1 days 05:24:33,NaT

In [ ]:
'''
- koordinaten aus location einfügen
- inaccurate locations behandeln
- distanzen berechnen zwischen koordinaten
- outlier
- temporary shifts
- glätten
'''