In [1]:
import numpy as np
import pandas as pd

from glas_o_mat import dataset as ds

In [2]:
dataset = ds.create_dataset()

dataset.activities

,TRANSACTION_ID,CONTAINER_ID,SLIDER_LEVEL,CV_LEVEL,SENSOR_LEVEL,IMAGE_ID,PHONE_ID,RECORDED_AT,COMMENT,IS_EMPTIED,LATITUDE,LONGITUDE,CREATED_AT,UPDATED_AT,ROUTE_ID,LOCATION_ID,MATERIAL_ID,DATE,INTERVAL
0,2,1001101101100271211,20,NaN,NaN,1001101101100271211/2023-09-28T06:36:05.355751...,TP1A.220624.014_2,2023-09-26 06:36:05,NaN,1,49.455948,7.791700,2023-10-13 11:18:58.0,NaN,NaN,100110110110027,12,2023-09-26,NaN
1,1,1001101101100271111,30,NaN,NaN,1001101101100271111/2023-09-28T06:36:48.022095...,TP1A.220624.014_2,2023-09-26 06:36:48,NaN,1,49.455948,7.791700,2023-10-13 11:18:58.0,NaN,NaN,100110110110027,11,2023-09-26,43.0
2,3,1001101101100271311,10,NaN,NaN,1001101101100271311/2023-09-28T06:37:16.029149...,TP1A.220624.014_2,2023-09-26 06:37:16,NaN,0,49.455948,7.791700,2023-10-13 11:18:58.0,NaN,NaN,100110110110027,13,2023-09-26,28.0
3,6,1001101101100191311,10,NaN,NaN,1001101101100191311/2023-09-28T06:50:59.338075...,TP1A.220624.014_2,2023-09-26 06:50:59,NaN,0,49.448544,7.769812,2023-10-13 11:18:58.0,NaN,NaN,100110110110019,13,2023-09-26,823.0
4,4,1001101101100191111,0,NaN,NaN,1001101101100191111/2023-09-28T06:51:15.117682...,TP1A.220624.014_2,2023-09-26 06:51:15,NaN,0,49.448544,7.769812,2023-10-13 11:18:58.0,NaN,NaN,100110110110019,11,2023-09-26,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41458,61152,1001101101100531212,90,NaN,NaN,1001101101100531212/2024-10-17T14:46:54.523517...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-17 14:46:55,NaN,1,49.494200,49.494200,2024-10-17 12:47:33.0,2024-10-17 12:47:33.0,2024-10-17-1001101101-0,100110110110053,12,2024-10-17,11.0
41459,61149,1001101101100531111,90,NaN,NaN,1001101101100531111/2024-10-17T14:47:02.646031...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-17 14:47:03,NaN,1,49.494200,49.494200,2024-10-17 12:47:31.0,2024-10-17 12:47:31.0,2024-10-17-1001101101-0,100110110110053,11,2024-10-17,8.0
41460,61150,1001101101100531112,90,NaN,NaN,1001101101100531112/2024-10-17T14:47:10.767846...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-17 14:47:11,NaN,1,49.494200,49.494200,2024-10-17 12:47:32.0,2024-10-17 12:47:32.0,2024-10-17-1001101101-0,100110110110053,11,2024-10-17,8.0
41461,61153,1001101101100531311,20,NaN,NaN,1001101101100531311/2024-10-17T14:47:19.611355...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-17 14:47:20,NaN,0,49.494200,49.494200,2024-10-17 12:47:34.0,2024-10-17 12:47:34.0,2024-10-17-1001101101-0,100110110110053,13,2024-10-17,9.0
41462,61154,1001101101100531312,10,NaN,NaN,1001101101100531312/2024-10-17T14:47:27.912185...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-17 14:47:28,NaN,0,49.494200,49.494200,2024-10-17 12:47:35.0,2024-10-17 12:47:35.0,2024-10-17-1001101101-0,100110110110053,13,2024-10-17,8.0

In [10]:
locations = dataset.activities.groupby(['LOCATION_ID', 'MATERIAL_ID'])
g = locations.get_group((100110110110020, 13)).drop_duplicates(['DATE', 'CONTAINER_ID'])
g[g['DATE'] >= '2024-05-06']

,TRANSACTION_ID,CONTAINER_ID,SLIDER_LEVEL,CV_LEVEL,SENSOR_LEVEL,IMAGE_ID,PHONE_ID,RECORDED_AT,COMMENT,IS_EMPTIED,LATITUDE,LONGITUDE,CREATED_AT,UPDATED_AT,ROUTE_ID,LOCATION_ID,MATERIAL_ID,DATE,INTERVAL
22611,28115,1001101101100201311,40,NaN,NaN,1001101101100201311/2024-05-06T12:48:27.999494...,UP1A.231005.007_6695359986a10fa0,2024-05-06 12:48:28,NaN,0,49.430013,7.771647,NaN,NaN,NaN,100110110110020,13,2024-05-06,16.0
22612,28116,1001101101100201312,30,NaN,NaN,1001101101100201312/2024-05-06T12:48:37.947264...,UP1A.231005.007_6695359986a10fa0,2024-05-06 12:48:38,NaN,0,49.430013,7.771647,NaN,NaN,NaN,100110110110020,13,2024-05-06,10.0
22613,28117,1001101101100201313,40,NaN,NaN,1001101101100201313/2024-05-06T12:49:08.203872...,UP1A.231005.007_6695359986a10fa0,2024-05-06 12:49:08,NaN,0,49.430013,7.771647,NaN,NaN,NaN,100110110110020,13,2024-05-06,30.0
23229,28768,1001101101100201311,80,NaN,NaN,1001101101100201311/2024-05-13T13:14:42.521835...,UP1A.231005.007_6695359986a10fa0,2024-05-13 13:14:43,NaN,0,49.429920,7.771588,NaN,NaN,NaN,100110110110020,13,2024-05-13,11.0
23230,28769,1001101101100201312,30,NaN,NaN,1001101101100201312/2024-05-13T13:14:55.856701...,UP1A.231005.007_6695359986a10fa0,2024-05-13 13:14:56,NaN,0,49.429920,7.771588,NaN,NaN,NaN,100110110110020,13,2024-05-13,13.0
24886,30452,1001101101100201311,30,NaN,NaN,1001101101100201311/2024-05-27T12:27:22.999635...,UP1A.231005.007_6695359986a10fa0,2024-05-27 12:27:23,NaN,0,49.429961,7.771604,NaN,NaN,NaN,100110110110020,13,2024-05-27,14.0
24887,30453,1001101101100201312,30,NaN,NaN,1001101101100201312/2024-05-27T12:27:31.904004...,UP1A.231005.007_6695359986a10fa0,2024-05-27 12:27:32,NaN,0,49.429961,7.771604,NaN,NaN,NaN,100110110110020,13,2024-05-27,9.0
25769,31350,1001101101100201311,70,NaN,NaN,1001101101100201311/2024-06-03T13:19:46.627365...,UP1A.231005.007_6695359986a10fa0,2024-06-03 13:19:47,NaN,0,49.429847,7.771452,NaN,NaN,NaN,100110110110020,13,2024-06-03,12.0
25770,31351,1001101101100201312,40,NaN,NaN,1001101101100201312/2024-06-03T13:20:03.871477...,UP1A.231005.007_6695359986a10fa0,2024-06-03 13:20:04,NaN,0,49.429847,7.771452,NaN,NaN,NaN,100110110110020,13,2024-06-03,17.0
26735,32314,1001101101100201311,90,NaN,NaN,1001101101100201311/2024-06-10T13:13:55.504933...,UP1A.231005.007_6695359986a10fa0,2024-06-10 13:13:56,NaN,0,49.429973,7.771603,NaN,NaN,NaN,100110110110020,13,2024-06-10,12.0
26736,32315,1001101101100201312,30,NaN,NaN,1001101101100201312/2024-06-10T13:14:06.217684...,UP1A.231005.007_6695359986a10fa0,2024-06-10 13:14:06,NaN,0,49.429973,7.771603,NaN,NaN,NaN,100110110110020,13,2024-06-10,10.0
27407,32975,1001101101100201311,30,NaN,NaN,1001101101100201311/2024-06-13T12:31:47.987532...,UP1A.231005.007_6695359986a10fa0,2024-06-13 12:31:48,NaN,1,49.429962,7.771668,NaN,NaN,NaN,100110110110020,13,2024-06-13,529.0
27408,32976,1001101101100201312,80,NaN,NaN,1001101101100201312/2024-06-13T12:31:58.081838...,UP1A.231005.007_6695359986a10fa0,2024-06-13 12:31:58,NaN,1,49.429962,7.771668,NaN,NaN,NaN,100110110110020,13,2024-06-13,10.0
27770,33348,1001101101100201311,30,NaN,NaN,1001101101100201311/2024-06-17T13:33:52.049319...,UP1A.231005.007_6695359986a10fa0,2024-06-17 13:33:52,NaN,0,49.430033,7.770998,NaN,NaN,NaN,100110110110020,13,2024-06-17,14.0
27771,33349,1001101101100201312,20,NaN,NaN,1001101101100201312/2024-06-17T13:34:00.991787...,UP1A.231005.007_6695359986a10fa0,2024-06-17 13:34:01,NaN,0,49.430033,7.770998,NaN,NaN,NaN,100110110110020,13,2024-06-17,9.0
28835,34412,1001101101100201311,60,NaN,NaN,1001101101100201311/2024-06-24T13:28:34.770662...,UP1A.231005.007_6695359986a10fa0,2024-06-24 13:28:35,NaN,0,49.429897,7.771593,NaN,NaN,NaN,100110110110020,13,2024-06-24,8.0
28836,34413,1001101101100201312,20,NaN,NaN,1001101101100201312/2024-06-24T13:28:44.497149...,UP1A.231005.007_6695359986a10fa0,2024-06-24 13:28:44,NaN,0,49.429897,7.771593,NaN,NaN,NaN,100110110110020,13,2024-06-24,9.0
29702,35281,1001101101100201311,70,NaN,NaN,1001101101100201311/2024-07-01T13:27:00.482548...,UP1A.231005.007_6695359986a10fa0,2024-07-01 13:27:00,NaN,0,49.429922,7.771662,NaN,NaN,NaN,100110110110020,13,2024-07-01,8.0
29703,35282,1001101101100201312,30,NaN,NaN,1001101101100201312/2024-07-01T13:27:08.331984...,UP1A.231005.007_6695359986a10fa0,2024-07-01 13:27:08,NaN,0,49.429922,7.771662,NaN,NaN,NaN,100110110110020,13,2024-07-01,8.0
30972,50601,1001101101100201311,100,NaN,NaN,1001101101100201311/2024-07-12T10:39:48.418710...,UP1A.231005.007_6695359986a10fa0,2024-07-12 10:39:48,NaN,1,49.429813,7.771868,2024-07-12 08:40:05.0,2024-09-30 15:32:27.0,2024-07-12-1001101101-0,100110110110020,13,2024-07-12,200.0
31063,50698,1001101101100201311,10,NaN,NaN,1001101101100201311/2024-08-01T08:30:39.894399...,UP1A.231005.007_6695359986a10fa0,2024-07-15 08:30:40,NaN,0,49.429960,7.771598,2024-07-15 06:31:25.0,2024-09-30 15:32:27.0,2024-07-15-1001101101-0,100110110110020,13,2024-07-15,53.0
31064,50699,1001101101100201312,0,NaN,NaN,1001101101100201312/2024-08-01T08:30:53.870452...,UP1A.231005.007_6695359986a10fa0,2024-07-15 08:30:54,NaN,0,49.429960,7.771598,2024-07-15 06:31:28.0,2024-09-30 15:32:27.0,2024-07-15-1001101101-0,100110110110020,13,2024-07-15,14.0
32717,52360,1001101101100201311,10,NaN,NaN,1001101101100201311/2024-07-29T11:04:30.178103...,UP1A.231005.007_feb67a335a9479a4,2024-07-29 11:04:30,NaN,0,49.430016,49.430016,2024-07-29 09:04:53.0,2024-09-30 15:32:27.0,2024-07-29-1001101101-0,100110110110020,13,2024-07-29,8.0
32718,52361,1001101101100201312,10,NaN,NaN,1001101101100201312/2024-07-29T11:04:37.522855...,UP1A.231005.007_feb67a335a9479a4,2024-07-29 11:04:38,NaN,0,49.430018,49.430018,2024-07-29 09:04:54.0,2024-09-30 15:32:27.0,2024-07-29-1001101101-0,100110110110020,13,2024-07-29,8.0
33093,52746,1001101101100201311,20,NaN,NaN,1001101101100201311/2024-07-30T14:04:37.677319...,UP1A.231005.007_feb67a335a9479a4,2024-07-30 14:04:38,NaN,1,49.429778,49.429778,2024-07-30 12:05:24.0,2024-09-30 15:32:27.0,2024-07-30-1001101101-0,100110110110020,13,2024-07-30,793.0
33094,52747,1001101101100201312,10,NaN,NaN,1001101101100201312/2024-07-30T14:04:44.872204...,UP1A.231005.007_feb67a335a9479a4,2024-07-30 14:04:45,NaN,1,49.430091,49.430091,2024-07-30 12:05:24.0,2024-09-30 15:32:27.0,2024-07-30-1001101101-0,100110110110020,13,2024-07-30,7.0
34197,53827,1001101101100201311,20,NaN,NaN,1001101101100201311/2024-08-08T13:08:31.002065...,UP1A.231005.007_feb67a335a9479a4,2024-08-08 13:08:31,NaN,0,49.430040,49.430040,2024-08-08 11:18:32.0,2024-09-30 15:32:27.0,2024-08-08-1001101101-0,100110110110020,13,2024-08-08,10.0
34198,53828,1001101101100201312,10,NaN,NaN,1001101101100201312/2024-08-08T13:08:37.824416...,UP1A.231005.007_feb67a335a9479a4,2024-08-08 13:08:38,NaN,0,49.430054,49.430054,2024-08-08 11:18:34.0,2024-09-30 15:32:27.0,2024-08-08-1001101101-0,100110110110020,13,2024-08-08,7.0
35018,54648,1001101101100201311,30,NaN,NaN,1001101101100201311/2024-08-16T07:25:57.043042...,UP1A.231005.007_feb67a335a9479a4,2024-08-16 07:25:57,NaN,1,49.430048,49.430048,2024-08-16 05:39:10.0,2024-09-30 15:32:27.0,2024-08-16-1001101101-0,100110110110020,13,2024-08-16,10.0
35019,54649,1001101101100201312,20,NaN,NaN,1001101101100201312/2024-08-16T07:26:08.234950...,UP1A.231005.007_feb67a335a9479a4,2024-08-16 07:26:08,NaN,1,49.430127,49.430127,2024-08-16 05:39:11.0,2024-09-30 15:32:27.0,2024-08-16-1001101101-0,100110110110020,13,2024-08-16,11.0
35314,54942,1001101101100201311,20,NaN,NaN,1001101101100201311/2024-08-19T09:06:16.524109...,UP1A.231005.007_feb67a335a9479a4,2024-08-19 09:06:17,NaN,0,49.430019,49.430019,2024-08-19 07:06:40.0,2024-09-30 15:32:27.0,2024-08-19-1001101101-0,100110110110020,13,2024-08-19,10.0
35315,54943,1001101101100201312,0,NaN,NaN,1001101101100201312/2024-08-19T09:06:33.132415...,UP1A.231005.007_feb67a335a9479a4,2024-08-19 09:06:33,NaN,1,49.430057,49.430057,2024-08-19 07:06:41.0,2024-09-30 15:32:27.0,2024-08-19-1001101101-0,100110110110020,13,2024-08-19,16.0
36718,56368,1001101101100201311,60,NaN,NaN,1001101101100201311/2024-08-29T09:30:06.773245...,UP1A.231005.007_feb67a335a9479a4,2024-08-29 09:30:07,NaN,0,49.430034,49.430034,2024-08-29 07:38:42.0,2024-09-30 15:32:27.0,2024-08-29-1001101101-0,100110110110020,13,2024-08-29,10.0
36719,56369,1001101101100201312,30,NaN,NaN,1001101101100201312/2024-08-29T09:30:14.983670...,UP1A.231005.007_feb67a335a9479a4,2024-08-29 09:30:15,NaN,0,49.429988,49.429988,2024-08-29 07:38:44.0,2024-09-30 15:32:27.0,2024-08-29-1001101101-0,100110110110020,13,2024-08-29,8.0
37720,57378,1001101101100201311,70,NaN,NaN,1001101101100201311/2024-09-09T09:03:29.719934...,UP1A.231005.007_feb67a335a9479a4,2024-09-09 09:03:30,NaN,0,49.429926,49.429926,2024-09-09 07:03:46.0,2024-09-30 15:32:27.0,2024-09-09-1001101101-0,100110110110020,13,2024-09-09,8.0
37721,57379,1001101101100201312,30,NaN,NaN,1001101101100201312/2024-09-09T09:03:39.740237...,UP1A.231005.007_feb67a335a9479a4,2024-09-09 09:03:40,NaN,0,49.429994,49.429994,2024-09-09 07:03:47.0,2024-09-30 15:32:27.0,2024-09-09-1001101101-0,100110110110020,13,2024-09-09,10.0
38947,58635,1001101101100201311,100,NaN,NaN,1001101101100201311/2024-09-20T09:13:46.568239...,UP1A.231005.007_5ca2d1957972238e,2024-09-20 09:13:47,NaN,0,0.000000,0.000000,2024-09-20 07:14:04.0,2024-09-30 15:32:27.0,2024-09-20-1001101101-0,100110110110020,13,2024-09-20,16.0
38948,58636,1001101101100201312,30,NaN,NaN,1001101101100201312/2024-09-20T09:13:57.511077...,UP1A.231005.007_5ca2d1957972238e,2024-09-20 09:13:58,NaN,0,0.000000,0.000000,2024-09-20 07:14:04.0,2024-09-30 15:32:27.0,2024-09-20-1001101101-0,100110110110020,13,2024-09-20,11.0
39843,59535,1001101101100201311,100,NaN,NaN,1001101101100201311/2024-10-01T08:36:58.219884...,UP1A.231005.007_5ca2d1957972238e,2024-10-01 08:36:58,NaN,0,0.000000,0.000000,2024-10-01 06:37:16.0,2024-10-01 06:37:16.0,2024-10-01-1001101101-0,100110110110020,13,2024-10-01,9.0
39844,59536,1001101101100201312,50,NaN,NaN,1001101101100201312/2024-10-01T08:37:08.178980...,UP1A.231005.007_5ca2d1957972238e,2024-10-01 08:37:08,NaN,0,0.000000,0.000000,2024-10-01 06:37:17.0,2024-10-01 06:37:17.0,2024-10-01-1001101101-0,100110110110020,13,2024-10-01,10.0
40711,60403,1001101101100201311,100,NaN,NaN,1001101101100201311/2024-10-10T08:14:37.980932...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-10 08:14:38,NaN,0,49.429992,49.429992,2024-10-10 06:14:55.0,2024-10-10 06:14:55.0,2024-10-10-1001101101-0,100110110110020,13,2024-10-10,21.0
40712,60404,1001101101100201312,80,NaN,NaN,1001101101100201312/2024-10-10T08:14:48.078422...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-10 08:14:48,NaN,0,49.429992,49.429992,2024-10-10 06:14:57.0,2024-10-10 06:14:57.0,2024-10-10-1001101101-0,100110110110020,13,2024-10-10,10.0
41242,60938,1001101101100201311,100,NaN,NaN,1001101101100201311/2024-10-16T13:22:43.241404...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-16 13:22:43,NaN,1,49.494200,49.494200,2024-10-16 11:23:44.0,2024-10-16 11:23:44.0,2024-10-16-1001101101-0,100110110110020,13,2024-10-16,181.0
41243,60939,1001101101100201312,100,NaN,NaN,1001101101100201312/2024-10-16T13:22:51.023758...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-16 13:22:51,NaN,1,49.494200,49.494200,2024-10-16 11:23:45.0,2024-10-16 11:23:45.0,2024-10-16-1001101101-0,100110110110020,13,2024-10-16,8.0
41324,61016,1001101101100201311,10,NaN,NaN,1001101101100201311/2024-10-17T07:34:22.805395...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-17 07:34:23,NaN,0,49.494200,49.494200,2024-10-17 05:34:36.0,2024-10-17 05:34:36.0,2024-10-17-1001101101-0,100110110110020,13,2024-10-17,11.0
41325,61017,1001101101100201312,10,NaN,NaN,1001101101100201312/2024-10-17T07:34:30.067422...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-17 07:34:30,NaN,0,49.494200,49.494200,2024-10-17 05:34:37.0,2024-10-17 05:34:37.0,2024-10-17-1001101101-0,100110110110020,13,2024-10-17,7.0

In [4]:
dataset.locations

,LOCATION_ID,GEO_LAT,GEO_LON,LOCATION_NAME,CITY,STREET,POSTALCODE,IS_ACTIVE,DISPOSITION_AREA_ID,ACCESS_TYPE,HAS_POSITION_CHANGED
0,100110110101,49.493983,7.844887,Jakob Becker Mehlingen,Mehlingen,An d. Heide 10,67678,1,1.001101e+09,private,0
1,100110110191,49.503797,7.851304,Schirmbeck,Mehlingen,Lindberg-Allee 45,67678,1,1.001101e+09,private,0
2,100110110201,49.493983,7.844887,Jakob Becker Mehlingen,Mehlingen,An d. Heide 10,67678,1,1.001101e+09,private,0
3,100110110291,49.503797,7.851304,Schirmbeck,Mehlingen,Lindberg-Allee 45,67678,1,1.001101e+09,private,0
4,100110210191,-1.000000,-1.000000,Unknown Location,Unknown City,Unknown Street,00000,1,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...
395,100310110101104,50.258766,9.009344,Recyclinghof A,Metropolis,Alte Straße 38,54321,1,1.003101e+09,public,0
396,100310110101105,52.049840,8.993340,Brandenburger Tor,Metropolis,Morgenstraße 89,54321,1,1.003101e+09,public,0
397,100310110101106,51.911000,8.809850,Theater,Metropolis,Poststraße 4,54321,1,1.003101e+09,public,0
398,100310110101107,51.110000,8.808500,Einkaufszentrum,Metropolis,Poststraße 30,54321,1,1.003101e+09,public,0
399,100310110101108,51.100000,8.085000,Cafe Mert,Metropolis,Lessingstraße 1a,54321,1,1.003101e+09,public,0

In [8]:
merged = pd.merge(dataset.activities, dataset.locations, on='LOCATION_ID', how='left')
merged

KeyError: 'MATERIAL_ID'

In [6]:
merged[merged['GEO_LAT'].isna()]

,TRANSACTION_ID,CONTAINER_ID,SLIDER_LEVEL,CV_LEVEL,SENSOR_LEVEL,IMAGE_ID,PHONE_ID,RECORDED_AT,COMMENT,IS_EMPTIED,...,GEO_LAT,GEO_LON,LOCATION_NAME,CITY,STREET,POSTALCODE,IS_ACTIVE,DISPOSITION_AREA_ID,ACCESS_TYPE,HAS_POSITION_CHANGED
14375,19911,100110199991311,30,NaN,NaN,100110199991311/2024-03-08T07:05:15.305631.png,TP1A.220624.014,2024-03-08 07:05:15,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14376,19882,100110199991111,20,NaN,NaN,100110199991111/2024-03-08T07:05:22.791233.png,TP1A.220624.014,2024-03-08 07:05:23,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14377,19910,100110199991211,20,NaN,NaN,100110199991211/2024-03-08T07:05:31.082068.png,TP1A.220624.014,2024-03-08 07:05:31,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37774,57439,1001101102001211,20,NaN,NaN,1001101102001211/2024-09-09T11:27:00.764327.png,TP1A.220624.014_98095b3e98165f92,2024-09-09 11:27:01,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37775,57438,1001101102001111,50,NaN,NaN,1001101102001111/2024-09-09T11:27:25.609646.png,TP1A.220624.014_98095b3e98165f92,2024-09-09 11:27:26,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37776,57440,1001101102001311,50,NaN,NaN,1001101102001311/2024-09-09T11:27:35.617210.png,TP1A.220624.014_98095b3e98165f92,2024-09-09 11:27:36,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38044,57713,1002101101001211,80,NaN,NaN,1002101101001211/2024-09-12T07:05:16.163068.png,UP1A.231005.007_7fdea449d3ec0b02,2024-09-12 07:05:16,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38045,57711,1002101101001111,60,NaN,NaN,1002101101001111/2024-09-12T07:05:31.913553.png,UP1A.231005.007_7fdea449d3ec0b02,2024-09-12 07:05:32,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38046,57712,1002101101001112,60,NaN,NaN,1002101101001112/2024-09-12T07:06:01.549901.png,UP1A.231005.007_7fdea449d3ec0b02,2024-09-12 07:06:02,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38414,58089,1002101101001111,70,NaN,NaN,1002101101001111/2024-09-16T09:37:18.058481.png,UP1A.231005.007_31d25da526bfcac3,2024-09-16 09:37:18,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38415,58091,1002101101001311,100,NaN,NaN,1002101101001311/2024-09-16T09:37:24.696054.png,UP1A.231005.007_31d25da526bfcac3,2024-09-16 09:37:25,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38416,58090,1002101101001211,30,NaN,NaN,1002101101001211/2024-09-16T09:37:32.406390.png,UP1A.231005.007_31d25da526bfcac3,2024-09-16 09:37:32,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38457,58132,1002101101001311,60,NaN,NaN,1002101101001311/2024-09-17T06:50:19.954123.png,UP1A.231005.007_7fdea449d3ec0b02,2024-09-17 06:50:20,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38547,58222,1002101101031111,60,NaN,NaN,1002101101031111/2024-09-17T08:45:56.846872.png,UP1A.231005.007_7fdea449d3ec0b02,2024-09-17 08:45:57,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38548,58223,1002101101031311,50,NaN,NaN,1002101101031311/2024-09-17T08:46:05.615798.png,UP1A.231005.007_7fdea449d3ec0b02,2024-09-17 08:46:06,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38621,58298,1002101101041211,110,NaN,NaN,1002101101041211/2024-09-17T11:30:52.981882.png,UP1A.231005.007_7fdea449d3ec0b02,2024-09-17 11:30:53,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38622,58299,1002101101041311,60,NaN,NaN,1002101101041311/2024-09-17T11:31:00.929167.png,UP1A.231005.007_7fdea449d3ec0b02,2024-09-17 11:31:01,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38623,58297,1002101101041111,110,NaN,NaN,1002101101041111/2024-09-17T11:31:09.303617.png,UP1A.231005.007_7fdea449d3ec0b02,2024-09-17 11:31:09,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39970,59661,1002101101001311,80,NaN,NaN,1002101101001311/2024-10-01T13:10:30.483585.png,UP1A.231005.007_ee9e05ac1e43740b,2024-10-01 13:10:30,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40115,59807,1002101101001311,70,NaN,NaN,1002101101001311/2024-10-02T09:37:06.722803.png,UP1A.231005.007_ee9e05ac1e43740b,2024-10-02 09:37:07,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40176,59868,1002101101011311,60,NaN,NaN,1002101101011311/2024-10-02T11:51:22.034057.png,UP1A.231005.007_ee9e05ac1e43740b,2024-10-02 11:51:22,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40394,60118,1001101102101971111,60,NaN,NaN,NaN,TP1A.220624.014_98095b3e98165f92,2024-10-04 11:30:01,inserted manually due to broken phone,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40395,60119,1001101102101971211,40,NaN,NaN,NaN,TP1A.220624.014_98095b3e98165f92,2024-10-04 11:30:01,inserted manually due to broken phone,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40396,60120,1001101102101971311,10,NaN,NaN,NaN,TP1A.220624.014_98095b3e98165f92,2024-10-04 11:30:01,inserted manually due to broken phone,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40397,60121,1001101102101971112,50,NaN,NaN,NaN,TP1A.220624.014_98095b3e98165f92,2024-10-04 11:30:01,inserted manually due to broken phone,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40398,60122,1001101102101971212,40,NaN,NaN,NaN,TP1A.220624.014_98095b3e98165f92,2024-10-04 11:30:01,inserted manually due to broken phone,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40399,60123,1001101102101971312,100,NaN,NaN,NaN,TP1A.220624\n.014_98095b3e98165f92,2024-10-04 11:30:01,inserted manually due to broken phone,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40412,60098,1002101101001311,110,NaN,NaN,1002101101001311/2024-10-04T12:59:47.383427.png,UP1A.231005.007_ee9e05ac1e43740b,2024-10-04 12:59:47,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
containers

NameError: name 'containers' is not defined

In [7]:
t = dataset.activities.copy()
t[(t['LOCATION_ID'] == 100110110110038)]

,TRANSACTION_ID,CONTAINER_ID,SLIDER_LEVEL,CV_LEVEL,SENSOR_LEVEL,IMAGE_ID,PHONE_ID,RECORDED_AT,COMMENT,IS_EMPTIED,LATITUDE,LONGITUDE,CREATED_AT,UPDATED_AT,ROUTE_ID,LOCATION_ID,INTERVAL
72,103,1001101101100381311,10,NaN,NaN,1001101101100381311/2023-09-28T11:40:41.820991...,TP1A.220624.014_2,2023-09-26 11:40:42,NaN,0,49.449627,7.739105,2023-10-13 11:18:58.0,NaN,NaN,100110110110038,725.0
73,101,1001101101100381111,20,NaN,NaN,1001101101100381111/2023-09-28T11:40:53.042403...,TP1A.220624.014_2,2023-09-26 11:40:53,NaN,1,49.449627,7.739105,2023-10-13 11:18:58.0,NaN,NaN,100110110110038,11.0
74,102,1001101101100381211,10,NaN,NaN,1001101101100381211/2023-09-28T11:41:05.572700...,TP1A.220624.014_2,2023-09-26 11:41:06,NaN,1,49.449627,7.739105,2023-10-13 11:18:58.0,NaN,NaN,100110110110038,13.0
981,2028,1001101101100381311,10,NaN,NaN,1001101101100381311/2023-10-12T09:33:40.661502...,TP1A.220624.014_2,2023-10-10 09:33:41,NaN,0,49.449402,7.739309,2023-10-13 11:18:58.0,NaN,NaN,100110110110038,639.0
982,2026,1001101101100381111,10,NaN,NaN,1001101101100381111/2023-10-12T09:33:53.849178...,TP1A.220624.014_2,2023-10-10 09:33:54,NaN,1,49.449402,7.739309,2023-10-13 11:18:58.0,NaN,NaN,100110110110038,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39525,59213,1001101101100381111,40,NaN,NaN,1001101101100381111/2024-09-26T13:16:15.433714...,UP1A.231005.007_5ca2d1957972238e,2024-09-26 13:16:15,NaN,1,0.000000,0.000000,2024-09-26 11:16:33.0,2024-09-30 15:32:27.0,2024-09-26-1001101101-0,100110110110038,4.0
39526,59214,1001101101100381211,20,NaN,NaN,1001101101100381211/2024-09-26T13:16:28.657807...,UP1A.231005.007_5ca2d1957972238e,2024-09-26 13:16:29,NaN,1,0.000000,0.000000,2024-09-26 11:16:34.0,2024-09-30 15:32:27.0,2024-09-26-1001101101-0,100110110110038,14.0
41439,61133,1001101101100381311,70,NaN,NaN,1001101101100381311/2024-10-17T13:47:54.800294...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-17 13:47:55,NaN,0,49.494200,49.494200,2024-10-17 11:48:18.0,2024-10-17 11:48:18.0,2024-10-17-1001101101-0,100110110110038,1234.0
41440,61131,1001101101100381111,60,NaN,NaN,1001101101100381111/2024-10-17T13:48:05.437167...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-17 13:48:05,NaN,1,49.494200,49.494200,2024-10-17 11:48:17.0,2024-10-17 11:48:17.0,2024-10-17-1001101101-0,100110110110038,10.0
41441,61132,1001101101100381211,40,NaN,NaN,1001101101100381211/2024-10-17T13:48:13.059612...,UP1A.231005.007_0a1ae090352d8dcc,2024-10-17 13:48:13,NaN,1,49.494200,49.494200,2024-10-17 11:48:17.0,2024-10-17 11:48:17.0,2024-10-17-1001101101-0,100110110110038,8.0

In [8]:
filter = dataset.locations.groupby('LOCATION_ID').median()
filter

TypeError: agg function failed [how->median,dtype->object]

In [7]:
import pandas as pd
activities = pd.read_csv('../data/ContainerActivities.csv')
activities['PHONE_ID'] = activities['PHONE_ID'].astype(str)
activities[activities['PHONE_ID'].str.startswith('TKQ1')]

,TRANSACTION_ID,CONTAINER_ID,SLIDER_LEVEL,CV_LEVEL,SENSOR_LEVEL,IMAGE_ID,PHONE_ID,RECORDED_AT,COMMENT,IS_EMPTIED,LATITUDE,LONGITUDE,CREATED_AT,UPDATED_AT,ROUTE_ID
2344,4629,1001101102101211211,80,NaN,NaN,1001101102101211211/2023-10-25T10:46:26.918756...,TKQ1.220829.002_9557b6e88727d0ad,2023-10-25 10:46:27.0,NaN,1,49.009811,8.405240,2023-10-25 08:46:34.0,NaN,NaN
2345,4630,1001101102101211111,100,NaN,NaN,1001101102101211111/2023-10-25T10:51:36.792095...,TKQ1.220829.002_9557b6e88727d0ad,2023-10-25 10:51:37.0,NaN,1,49.009913,8.405022,2023-10-25 08:51:56.0,NaN,NaN
2368,4746,1001101102101211111,40,NaN,NaN,1001101102101211111/2023-10-26T01:42:10.926125,TKQ1.220829.002,2023-10-26 01:42:11.0,NaN,0,49.009969,8.405138,2023-10-25 23:42:24.0,NaN,NaN
2369,4748,1001101102101211211,110,NaN,NaN,1001101102101211211/2023-10-26T01:43:39.649757,TKQ1.220829.002,2023-10-26 01:43:40.0,NaN,1,49.009926,8.405095,2023-10-25 23:44:05.0,NaN,NaN
2370,4749,1001101102101211311,110,NaN,NaN,1001101102101211311/2023-10-26T01:43:50.768192,TKQ1.220829.002,2023-10-26 01:43:51.0,NaN,1,49.009926,8.405095,2023-10-25 23:44:06.0,NaN,NaN
2594,5122,1001101101999991311,80,NaN,NaN,1001101101999991311/2023-10-31T10:42:06.177267...,TKQ1.220829.002_9557b6e88727d0ad,2023-10-31 10:42:06.0,NaN,1,49.009892,8.405072,2023-10-31 09:42:22.0,NaN,NaN
2609,5147,1001101101999991211,90,NaN,NaN,1001101101999991211/2023-10-31T11:42:43.117173...,TKQ1.220829.002_9557b6e88727d0ad,2023-10-31 11:42:43.0,NaN,1,49.009916,8.405000,2023-10-31 10:42:54.0,NaN,NaN
2610,5148,1001101101999991211,90,NaN,NaN,1001101101999991211/2023-10-31T11:42:43.117.png,TKQ1.220829.002_9557b6e88727d0ad,2023-10-31 11:42:43.0,NaN,1,49.009892,8.404999,2023-10-31 10:45:03.0,NaN,NaN
2611,5149,1001101102101211111,20,NaN,NaN,1001101102101211111/2023-10-31T12:00:32.745042...,TKQ1.220829.002_9557b6e88727d0ad,2023-10-31 12:00:33.0,NaN,1,49.009955,8.405150,2023-10-31 11:00:46.0,NaN,NaN
2612,5150,1001101102101211211,80,NaN,NaN,1001101102101211211/2023-10-31T12:00:29.262225...,TKQ1.220829.002_9557b6e88727d0ad,2023-10-31 12:00:29.0,NaN,1,49.009955,8.405150,2023-10-31 11:00:47.0,NaN,NaN
2613,5151,1001101102101211311,50,NaN,NaN,1001101102101211311/2023-10-31T12:00:24.845884...,TKQ1.220829.002_9557b6e88727d0ad,2023-10-31 12:00:25.0,NaN,1,49.009955,8.405150,2023-10-31 11:00:48.0,NaN,NaN
6436,9477,1001101102101211111,10,NaN,NaN,1001101102101211111/2023-12-18T12:48:07.230122...,TKQ1.220829.002_9557b6e88727d0ad,2023-12-18 12:48:07.0,NaN,1,49.009812,8.385591,2023-12-18 11:48:50.0,NaN,NaN
6437,9478,1001101102101211211,50,NaN,NaN,1001101102101211211/2023-12-18T12:47:45.889625...,TKQ1.220829.002_9557b6e88727d0ad,2023-12-18 12:47:46.0,NaN,1,49.009812,8.385591,2023-12-18 11:48:51.0,NaN,NaN
6438,9479,1001101102101211311,80,NaN,NaN,1001101102101211311/2023-12-18T12:48:17.687283...,TKQ1.220829.002_9557b6e88727d0ad,2023-12-18 12:48:18.0,NaN,0,49.009812,8.385591,2023-12-18 11:48:52.0,NaN,NaN
6439,9480,1001101102100241311,80,NaN,NaN,1001101102100241311/2023-12-18T12:49:05.169040...,TKQ1.220829.002_9557b6e88727d0ad,2023-12-18 12:49:05.0,NaN,1,49.009816,8.385575,2023-12-18 11:49:20.0,NaN,NaN
6929,10097,1001101102101211311,60,NaN,NaN,1001101102101211311/2023-12-21T15:50:43.532018...,TKQ1.220829.002_9557b6e88727d0ad,2023-12-21 15:50:44.0,NaN,1,49.009925,8.405209,2023-12-21 14:50:55.0,NaN,NaN
7134,10334,1001101102100231211,10,NaN,NaN,1001101102100231211/2023-12-24T17:35:52.519641...,TKQ1.220829.002_9557b6e88727d0ad,2023-12-24 17:35:53.0,NaN,0,48.437349,9.940808,2023-12-24 16:37:05.0,NaN,NaN
13184,17470,1002101101011001111,50,NaN,NaN,1002101101011001111/2024-02-28T11:12:04.540748...,TKQ1.220829.002_9557b6e88727d0ad,2024-02-28 11:12:05.0,|Philipp vor Ort,0,49.882073,8.656012,2024-02-28 10:12:54.0,NaN,NaN
13185,17471,1002101101011001211,50,NaN,NaN,1002101101011001211/2024-02-28T11:11:48.118933...,TKQ1.220829.002_9557b6e88727d0ad,2024-02-28 11:11:48.0,|Philipp vor Ort,0,49.882073,8.656012,2024-02-28 10:12:55.0,NaN,NaN
13186,17472,1002101101011001311,110,NaN,NaN,1002101101011001311/2024-02-28T11:11:24.866341...,TKQ1.220829.002_9557b6e88727d0ad,2024-02-28 11:11:25.0,|Philipp vor Ort,0,49.882073,8.656012,2024-02-28 10:12:56.0,NaN,NaN
13246,17606,1002101101011201111,10,NaN,NaN,1002101101011201111/2024-02-28T12:41:00.791583...,TKQ1.220829.002_9557b6e88727d0ad,2024-02-28 12:41:01.0,|Philipp vor ort,0,49.009932,8.405222,2024-02-28 16:37:01.0,NaN,NaN
13247,17607,1002101101011201211,20,NaN,NaN,1002101101011201211/2024-02-28T12:41:16.851618...,TKQ1.220829.002_9557b6e88727d0ad,2024-02-28 12:41:17.0,|Philipp vor ort,0,49.009932,8.405222,2024-02-28 16:37:02.0,NaN,NaN
13248,17608,1002101101011201311,40,NaN,NaN,1002101101011201311/2024-02-28T12:41:37.991622...,TKQ1.220829.002_9557b6e88727d0ad,2024-02-28 12:41:38.0,|Philipp vor ort,0,49.009932,8.405222,2024-02-28 16:37:03.0,NaN,NaN
13249,17609,1002101101011221111,20,NaN,NaN,1002101101011221111/2024-02-28T12:34:52.851619...,TKQ1.220829.002_9557b6e88727d0ad,2024-02-28 12:34:53.0,|Philipp vor ort,0,49.009932,8.405222,2024-02-28 16:37:04.0,NaN,NaN
13250,17610,1002101101011221211,20,NaN,NaN,1002101101011221211/2024-02-28T12:35:08.951366...,TKQ1.220829.002_9557b6e88727d0ad,2024-02-28 12:35:09.0,|Philipp vor ort,0,49.009932,8.405222,2024-02-28 16:37:05.0,NaN,NaN
13251,17611,1002101101011221311,20,NaN,NaN,1002101101011221311/2024-02-28T12:35:23.456996...,TKQ1.220829.002_9557b6e88727d0ad,2024-02-28 12:35:23.0,|Philipp vor ort,0,49.009932,8.405222,2024-02-28 16:37:06.0,NaN,NaN
22817,28332,1001101102100231111,20,NaN,NaN,1001101102100231111/2024-05-07T18:00:29.203289...,TKQ1.220829.002_9557b6e88727d0ad,2024-05-07 18:00:29.0,NaN,1,49.146968,9.216989,NaN,NaN,NaN
22818,28333,1001101102100231211,80,NaN,NaN,1001101102100231211/2024-05-07T17:59:53.401932...,TKQ1.220829.002_9557b6e88727d0ad,2024-05-07 17:59:53.0,NaN,1,49.146968,9.216989,NaN,NaN,NaN
22819,28334,1001101102100231311,100,NaN,NaN,1001101102100231311/2024-05-07T18:00:07.099112...,TKQ1.220829.002_9557b6e88727d0ad,2024-05-07 18:00:07.0,NaN,1,49.146968,9.216989,NaN,NaN,NaN
22820,28335,1001101102100231312,90,NaN,NaN,1001101102100231312/2024-05-07T18:00:12.657409...,TKQ1.220829.002_9557b6e88727d0ad,2024-05-07 18:00:13.0,NaN,1,49.146968,9.216989,NaN,NaN,NaN
22821,28336,1001101102100241111,90,NaN,NaN,1001101102100241111/2024-05-07T18:03:05.998966...,TKQ1.220829.002_9557b6e88727d0ad,2024-05-07 18:03:06.0,NaN,1,49.146959,9.216992,NaN,NaN,NaN
22822,28338,1001101102100231111,60,NaN,NaN,1001101102100231111/2024-05-07T18:16:20.278043...,TKQ1.220829.002_9557b6e88727d0ad,2024-05-07 18:16:20.0,NaN,1,49.146958,9.216996,NaN,NaN,NaN
22823,28339,1001101102100231211,80,NaN,NaN,1001101102100231211/2024-05-07T18:16:36.901535...,TKQ1.220829.002_9557b6e88727d0ad,2024-05-07 18:16:37.0,NaN,1,49.146957,9.217002,NaN,NaN,NaN
22824,28340,1001101102100231311,80,NaN,NaN,1001101102100231311/2024-05-07T18:16:43.718195...,TKQ1.220829.002_9557b6e88727d0ad,2024-05-07 18:16:44.0,NaN,1,49.146957,9.217002,NaN,NaN,NaN
22825,28341,1001101102100141111,110,NaN,NaN,1001101102100141111/2024-05-07T18:18:11.424516...,TKQ1.220829.002_9557b6e88727d0ad,2024-05-07 18:18:11.0,NaN,1,49.146959,9.216993,NaN,NaN,NaN
22826,28342,1002101101010521111,80,NaN,NaN,1002101101010521111/2024-05-07T18:22:07.286912...,TKQ1.220829.002_9557b6e88727d0ad,2024-05-07 18:22:07.0,NaN,1,49.146967,9.216986,NaN,NaN,NaN
22827,28343,1002101101011401311,110,NaN,NaN,1002101101011401311/2024-05-07T18:22:24.524763...,TKQ1.220829.002_9557b6e88727d0ad,2024-05-07 18:22:25.0,NaN,1,49.146956,9.216993,NaN,NaN,NaN
23270,28799,1001101102100231211,90,NaN,NaN,1001101102100231211/2024-05-13T19:59:02.779.png,TKQ1.220829.002_e7fa304d74fa831e,2024-05-13 19:59:03.0,NaN,1,49.007070,8.391688,NaN,NaN,NaN
23271,28802,1001101102101211111,100,NaN,NaN,1001101102101211111/2024-05-13T19:58:03.595.png,TKQ1.220829.002_e7fa304d74fa831e,2024-05-13 19:58:04.0,NaN,1,49.007070,8.391688,NaN,NaN,NaN
38215,57845,1003101101011041111,80,NaN,NaN,1003101101011041111/2024-09-19T12:44:27.142715...,TKQ1.220829.002_fd9239c5aed4a923,2024-09-19 12:44:27.0,NaN,1,49.015086,49.015086,2024-09-12 10:43:16.0,2024-09-12 10:43:16.0,NaN
38216,57846,1003101101011011311,40,NaN,NaN,1003101101011011311/2024-09-19T12:44:54.291662...,TKQ1.220829.002_fd9239c5aed4a923,2024-09-19 12:44:54.0,NaN,0,49.015071,49.015071,2024-09-12 10:43:44.0,2024-09-12 10:43:44.0,NaN
38217,57847,1003101101011021211,20,NaN,NaN,1003101101011021211/2024-09-19T12:46:12.862793...,TKQ1.220829.002_fd9239c5aed4a923,2024-09-19 12:46:13.0,NaN,0,49.015059,49.015059,2024-09-12 10:45:02.0,2024-09-12 10:45:02.0,NaN
38261,57891,1003101101011011111,40,NaN,NaN,1003101101011011111/2024-09-19T14:16:35.302531...,TKQ1.220829.002_fd9239c5aed4a923,2024-09-19 14:16:35.0,NaN,1,49.015088,49.015088,2024-09-12 12:16:11.0,2024-09-12 12:16:11.0,NaN
38262,57892,1003101101011011211,20,NaN,NaN,1003101101011011211/2024-09-19T14:17:02.395462...,TKQ1.220829.002_fd9239c5aed4a923,2024-09-19 14:17:02.0,NaN,0,49.015094,49.015094,2024-09-12 12:16:12.0,2024-09-12 12:16:12.0,NaN
38263,57893,1003101101011011311,70,NaN,NaN,1003101101011011311/2024-09-19T14:17:19.563733...,TKQ1.220829.002_fd9239c5aed4a923,2024-09-19 14:17:20.0,NaN,0,49.015093,49.015093,2024-09-12 12:16:13.0,2024-09-12 12:16:13.0,NaN

### TODO: drop rows which are recorded in an interval which is to close